kind: Pod
apiVersion: v1
metadata:
  name: mongo-replset
  labels:
    name: mongo-replset
spec:
  containers:
    - name: mongo-replset
      image: sinhasonalkumar/mongo-replset
      ports:
        - name: mongo-replset1
          containerPort: 27017
          hostPort : 27017

      volumeMounts:
        - name: ebsvol-inst1-replset1
          mountPath: /var/mongo/db
        - name: ebsvol-inst1-replset1
          mountPath: /var/mongo/log/

  volumes:
    - name: ebsvol-inst1-replset1
      awsElasticBlockStore:
         volumeID: vol-7f824fcb
         fsType: ext4 
